{
 "title": "customerflows",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Throughput per customer",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ipv6" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "throughputs",
     "query": "SELECT last(\"value\") FROM \"throughputs\" WHERE $timeFilter GROUP BY time($interval), \"ipv6\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current customer count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "janes_data",
     "select": [
      [
       { "params": [ "customer_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net_throughput",
     "query": "SELECT last(\"value\") FROM \"throughputs\" WHERE $timeFilter GROUP BY time($interval), \"ipv6\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current net throughput",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 5 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net_throughput",
     "query": "SELECT sum(\"throughputs\") FROM (\nSELECT derivative(last(\"value\"), 1s) *8 as throughputs FROM \"byte_count_in\" WHERE  time > now() - 10s GROUP BY time(10s), \"ipv6\" fill(null)\n)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jane's fairness index",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "janes_fairness_index",
     "query": "SELECT last(\"value\") FROM \"throughputs\" WHERE $timeFilter GROUP BY time($interval), \"ipv6\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current fairness index",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "janes_fairness_index",
     "query": "SELECT  \"net_throughput_squared\" / (\"customer_count\" * sum_squared_throughputs)  FROM \"janes_data\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}