name: terranet # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode #  <<<-DevMode needed due to Python multiprocessing opening files in /dev/shm


apps:
  terranet:
    command: bin/terranet
    plugs:
      - home
      - network-bind
      - network-control
      - network-manager
  clean:
    command: usr/bin/mn -c
    plugs:
      - network-control
      - network-manager

parts:
  komondor-snap:
    plugin: nil
    stage-snaps:
      - komondor
    organize:
      bin/komondor_main: bin/komondor
    prime:
      - bin/komondor

  openr-snap:
    plugin: nil
    stage-snaps:
      - openr/latest/beta
    prime:
      - sbin/openr
      - lib/
      - usr/lib/x86_64-linux-gnu/

  python-interpreter:
    plugin: nil
    stage-packages:
      - python
      - python-setuptools
      - python-pip
      - python-tk


  terranet:
    source: module
    plugin: python
    python-version: python2
    override-pull: |
      snapcraftctl pull
      sed -i 's|"ipmininet",||' setup.py
    after: ['ipmininet', 'komondor-snap', 'openr-snap']
    stage-packages:
      - curl
      - iperf

  mininet:
    plugin: nil
    stage-packages:
      - mininet
    after: ['python-interpreter']

  ipmininet:
    source: https://github.com/cnp3/ipmininet.git
    source-commit: d2ce6e12ceb78d8dc185088cde86acdb00d252a9
    plugin: python
    python-version: python2
    override-pull: |
      snapcraftctl pull
      sed -i "s|'mininet',||" setup.py
    after: ['python-interpreter', 'mininet']
    stage-packages: #Needed for sshd
      - openssh-client

